name = "hhmc-apocalypse"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58064a5dbd43aa8e0704a00d800ffaeefa0101e604ecf66aa23c49a7d4ea420d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
