name = "hhmc-apocalypse"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d160ba0f8a0ee6e5e3a17ccb0247f1104ba403fe09600fc84a111913a2ff6cde"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
