name = "hhmc-apocalypse"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a97f69293dc5315a7eb6c4aab9c743ae7f0ca519ea0ae3d2787dbb2704376ade"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
