name = "hhmc-apocalypse"
author = "Waveformal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b964fec0885e98542ee4e583bd79bd9024dc3de1a3305ca7bc9678057ab8a126"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
